---
version: "2"
services:
  app:
    build: .
    networks:
    - default
    ports:
    - 1323:1323
    env_file:
      - .env
    depends_on:
    - mongo
  mongo:
    image: mongo
    networks:
    - default
    volumes:
    - mongo_data:/data
    restart: on-failure
volumes:
  mongo_data:
networks:
  default: